### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by alex-x-crypto** [itzmeanjan/gasbot#3]
hi, thanks for your brilliant tool.

there is typo here
> txType ∈ {fastest, fast, avergae, safeLow}

average

**Comment by itzmeanjan** [comment]
Thanks @alex-x-crypto :+1:

**Comment by itzmeanjan** [comment]
I just fixed it in https://github.com/itzmeanjan/gasbot/commit/20f421d2f995e44f70b9f8c5b58c27773c2aba4d; closing this issue for now.
